# Generated by Django 4.1.7 on 2023-07-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('path', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('category', models.ManyToManyField(to='home.category')),
            ],
        ),
    ]
