# Generated by Django 4.1.7 on 2023-07-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domains',
            field=models.ManyToManyField(related_name='projects', to='home.category'),
        ),
    ]
