# Generated by Django 4.1.7 on 2023-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('label', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
