# Generated by Django 4.1.7 on 2023-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
